import os
from typing import List
from rust_fst import Map
from joblib import load


POLISH_STOPWORDS = [
    "a", "aby", "ach", "acz", "aczkolwiek", "aj", "akurat", "albo", "ale", "ależ", "ani", "aż", "bardziej", "bardzo",
    "bez", "bo", "bowiem", "by", "byli", "bym", "bynajmniej", "być", "był", "była", "było", "były", "będzie", "będą",
    "cali", "cała", "cały", "chce", "chcę", "choć", "ci", "ciebie", "cię", "co", "cokolwiek", "coraz", "coś", "czasami",
    "czasem", "czemu", "czy", "czyli", "często", "daleko", "dla", "dlaczego", "dlatego", "do", "dobrze", "dokąd",
    "dość", "dr", "dużo", "dwa", "dwaj", "dwie", "dwoje", "dzieki", "dzisiaj", "dziś", "gdy", "gdyby", "gdyż", "gdzie",
    "gdziekolwiek", "gdzieś", "go", "godz", "hab", "i", "ich", "ii", "iii", "ile", "im", "inna", "inne", "inny",
    "innych", "inż", "iv", "ix", "iż", "ja", "jak", "jakaś", "jakby", "jaki", "jakichś", "jakie", "jakiś", "jakiż",
    "jakkolwiek", "jako", "jakoś", "je", "jeden", "jedna", "jednak", "jednakże", "jedno", "jednym", "jedynie", "jego",
    "jej", "jemu", "jest", "jestem", "jeszcze", "jeśli", "jeżeli", "już", "ją", "każdy", "kiedy", "kierunku", "kilka",
    "kilku", "kimś", "kto", "ktokolwiek", "ktoś", "która", "które", "którego", "której", "który", "których", "którym",
    "którzy", "ku", "lat", "lecz", "lub", "ma", "mają", "mam", "mamy", "mgr", "mi", "miał", "mimo", "między", "mnie",
    "mną", "mogą", "moi", "moim", "moja", "moje", "może", "możliwe", "można", "mu", "musi", "my", "mój", "na", "nad",
    "nam", "nami", "nas", "nasi", "nasz", "nasza", "nasze", "naszego", "naszych", "natomiast", "natychmiast", "nawet",
    "nic", "nich", "nie", "niego", "niej", "niemu", "nigdy", "nim", "nimi", "nią", "niż", "no", "nowe", "np", "nr",
    "o", "o.o.", "obok", "od", "ok", "około", "on", "ona", "one", "oni", "ono", "oraz", "owszem", "pan", "pana", "pani",
    "pl", "po", "pod", "podczas", "pomimo", "ponad", "ponieważ", "potem", "powinien", "powinna", "powinni", "powinno",
    "poza", "prawie", "prof", "przecież", "przed", "przede", "przedtem", "przez", "przy", "raz", "razie", "roku",
    "również", "sam", "sama", "się", "skąd", "sobie", "sobą", "sposób", "swoje", "są", "ta", "tak", "taka", "taki",
    "takich", "takie", "także", "tam", "te", "tego", "tej", "tel", "temu", "ten", "teraz", "też", "to", "tobie",
    "tobą", "toteż", "totobą", "trzeba", "trochę", "tu", "tutaj", "twoi", "twoim", "twoja", "twoje", "twym", "twój",
    "ty", "tych", "tylko", "tym", "tys", "tzw", "tę", "tęw", "u", "ul", "vi", "vii", "viii", "vol", "w", "wam", "wami",
    "was", "wasi", "wasz", "wasza", "wasze", "wcale", "we", "według", "wie", "wiele", "wielu", "więc", "więcej", "wraz",
    "wszyscy", "wszystkich", "wszystkie", "wszystkim", "wszystko", "wtedy", "www", "wy", "właśnie", "wśród", "xi",
    "xii", "xiii", "xiv", "xv", "z", "za", "zanim", "zapewne", "zawsze", "zaś", "zanim", "ze", "zeznowu", "znów",
    "został", "zresztą", "zł", "żaden", "żadna", "żadne", "żadnych", "że", "żeby"
]

ENGLISH_STOPWORDS = [
    "a", "able", "about", "above", "according", "accordingly", "across", "actually", "after", "afterwards", "again",
    "against", "ain't", "all", "allow", "allows", "almost", "alone", "along", "already", "also", "although", "always",
    "am", "among", "amongst", "an", "and", "another", "any", "anybody", "anyhow", "anyone", "anything", "anyway",
    "anyways", "anywhere", "apart", "appear", "appreciate", "appropriate", "are", "aren't", "around", "as", "a's",
    "aside", "ask", "asking", "associated", "at", "available", "away", "awfully", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "behind", "being", "believe", "below", "beside", "besides",
    "best", "better", "between", "beyond", "both", "brief", "but", "by", "came", "can", "cannot", "cant", "can't",
    "cause", "causes", "certain", "certainly", "changes", "clearly", "c'mon", "co", "com", "come", "comes",
    "concerning", "consequently", "consider", "considering", "contain", "containing", "contains", "corresponding",
    "could", "couldn't", "course", "c's", "currently", "definitely", "described", "despite", "did", "didn't",
    "different", "do", "does", "doesn't", "doing", "don", "done", "don't", "down", "downwards", "during", "each",
    "edu", "eg", "eight", "either", "else", "elsewhere", "enough", "entirely", "especially", "et", "etc", "even",
    "ever", "every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example", "except", "far",
    "few", "fifth", "first", "five", "followed", "following", "follows", "for", "former", "formerly", "forth", "four",
    "from", "further", "furthermore", "get", "gets", "getting", "given", "gives", "go", "goes", "going", "gone", "got",
    "gotten", "greetings", "had", "hadn't", "happens", "hardly", "has", "hasn't", "have", "haven't", "having", "he",
    "he'd", "he'll", "hello", "help", "hence", "her", "here", "hereafter", "hereby", "herein", "here's", "hereupon",
    "hers", "herself", "he's", "hi", "him", "himself", "his", "hither", "hopefully", "how", "howbeit", "however",
    "how's", "i", "i'd", "ie", "if", "ignored", "i'll", "i'm", "immediate", "in", "inasmuch", "inc", "indeed",
    "insofar", "instead", "into", "inward", "is", "isn't", "it", "it'd", "it'll", "its", "it's", "itself", "i've",
    "just", "keep", "keeps", "kept", "know", "known", "knows", "last", "lately", "later", "latter", "latterly",
    "least", "less", "lest", "let", "let's", "like", "liked", "likely", "little", "look", "looking", "looks", "ltd",
    "mainly", "many", "may", "maybe", "me", "mean", "meanwhile", "merely", "might", "more", "moreover", "most",
    "mostly", "much", "must", "mustn't", "my", "myself", "name", "namely", "nd", "near", "nearly", "necessary",
    "need", "needs", "neither", "never", "nevertheless", "new", "next", "nine", "no", "nobody", "non", "none", "noone",
    "nor", "normally", "not", "nothing", "novel", "now", "nowhere", "obviously", "of", "off", "often", "oh", "ok",
    "okay", "old", "on", "once", "ones", "only", "onto", "or", "other", "others", "otherwise", "ought", "our", "ours",
    "ourselves", "out", "outside", "over", "overall", "own", "particular", "particularly", "per", "perhaps", "placed",
    "please", "plus", "possible", "presumably", "probably", "provides", "que", "quite", "qv", "rather", "rd", "re",
    "really", "reasonably", "regarding", "regardless", "regards", "relatively", "respectively", "right", "s", "said",
    "same", "saw", "say", "saying", "says", "second", "secondly", "see", "seeing", "seem", "seemed", "seeming",
    "seems", "seen", "self", "selves", "sensible", "sent", "serious", "seriously", "seven", "several", "shall",
    "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't", "since", "six", "so", "some", "somebody",
    "somehow", "someone", "something", "sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "specified",
    "specify", "specifying", "still", "sub", "such", "sup", "sure", "t", "take", "taken", "tell", "tends", "th",
    "than", "thank", "thanks", "thanx", "that", "thats", "that's", "the", "their", "theirs", "them", "themselves",
    "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "theres", "there's", "thereupon",
    "these", "they", "they'd", "they'll", "they're", "they've", "think", "third", "this", "thorough", "thoroughly",
    "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "took", "toward",
    "towards", "tried", "tries", "truly", "try", "trying", "t's", "twice", "two", "un", "under", "unfortunately",
    "unless", "unlikely", "until", "unto", "up", "upon", "us", "use", "used", "useful", "uses", "using", "usually",
    "value", "various", "very", "via", "viz", "vs", "want", "wants", "was", "wasn't", "way", "we", "we'd", "welcome",
    "well", "we'll", "went", "were", "we're", "weren't", "we've", "what", "whatever", "what's", "when", "whence",
    "whenever", "when's", "where", "whereafter", "whereas", "whereby", "wherein", "where's", "whereupon", "wherever",
    "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "who's", "whose", "why", "why's",
    "will", "willing", "wish", "with", "within", "without", "wonder", "won't", "would", "wouldn't", "yes", "yet",
    "you", "you'd", "you'll", "your", "you're", "yours", "yourself", "yourselves", "you've"
]

GERMAN_STOPWORDS = [
    "ab", "aber", "alle", "allein", "allem", "allen", "aller", "allerdings", "allerlei", "alles", "allmählich",
    "allzu", "als", "alsbald", "also", "am", "an", "and", "ander", "andere", "anderem", "anderen", "anderer",
    "andererseits", "anderes", "anderm", "andern", "andernfalls", "anders", "anstatt", "auch", "auf", "aus",
    "ausgenommen", "ausser", "ausserdem", "außer", "außerdem", "außerhalb", "bald", "bei", "beide", "beiden",
    "beiderlei", "beides", "beim", "beinahe", "bereits", "besonders", "besser", "beträchtlich", "bevor", "bezüglich",
    "bin", "bis", "bisher", "bislang", "bist", "bloß", "bsp.", "bzw", "ca", "ca.", "content", "da", "dabei", "dadurch",
    "dafür", "dagegen", "daher", "dahin", "damals", "damit", "danach", "daneben", "dann", "daran", "darauf", "daraus",
    "darin", "darum", "darunter", "darüber", "darüberhinaus", "das", "dass", "dasselbe", "davon", "davor", "dazu",
    "daß", "dein", "deine", "deinem", "deinen", "deiner", "deines", "dem", "demnach", "demselben", "den", "denen",
    "denn", "dennoch", "denselben", "der", "derart", "derartig", "derem", "deren", "derer", "derjenige", "derjenigen",
    "derselbe", "derselben", "derzeit", "des", "deshalb", "desselben", "dessen", "desto", "deswegen", "dich", "die",
    "diejenige", "dies", "diese", "dieselbe", "dieselben", "diesem", "diesen", "dieser", "dieses", "diesseits", "dir",
    "direkt", "direkte", "direkten", "direkter", "doch", "dort", "dorther", "dorthin", "drauf", "drin", "drunter",
    "drüber", "du", "dunklen", "durch", "durchaus", "eben", "ebenfalls", "ebenso", "eher", "eigenen", "eigenes",
    "eigentlich", "ein", "eine", "einem", "einen", "einer", "einerseits", "eines", "einfach", "einführen", "einführte",
    "einführten", "eingesetzt", "einig", "einige", "einigem", "einigen", "einiger", "einigermaßen", "einiges", "einmal",
    "eins", "einseitig", "einseitige", "einseitigen", "einseitiger", "einst", "einstmals", "einzig", "entsprechend",
    "entweder", "er", "erst", "es", "etc", "etliche", "etwa", "etwas", "euch", "euer", "eure", "eurem", "euren",
    "eurer", "eures", "falls", "fast", "ferner", "folgende", "folgenden", "folgender", "folgendes", "folglich", "fuer",
    "für", "gab", "ganze", "ganzem", "ganzen", "ganzer", "ganzes", "gar", "gegen", "gemäss", "ggf", "gleich",
    "gleichwohl", "gleichzeitig", "glücklicherweise", "gänzlich", "hab", "habe", "haben", "haette", "hast", "hat",
    "hatte", "hatten", "hattest", "hattet", "heraus", "herein", "hier", "hier", "hinter", "hiermit", "hiesige", "hin",
    "hinein", "hinten", "hinter", "hinterher", "http", "hätt", "hätte", "hätten", "höchstens", "ich", "igitt", "ihm",
    "ihn", "ihnen", "ihr", "ihre", "ihrem", "ihren", "ihrer", "ihres", "im", "immer", "immerhin", "in", "indem",
    "indessen", "infolge", "innen", "innerhalb", "ins", "insofern", "inzwischen", "irgend", "irgendeine", "irgendwas",
    "irgendwen", "irgendwer", "irgendwie", "irgendwo", "ist", "ja", "je", "jed", "jede", "jedem", "jeden",
    "jedenfalls", "jeder", "jederlei", "jedes", "jedoch", "jemand", "jene", "jenem", "jenen", "jener", "jenes",
    "jenseits", "jetzt", "jährig", "jährige", "jährigen", "jähriges", "kam", "kann", "kannst", "kaum", "kein", "keine",
    "keinem", "keinen", "keiner", "keinerlei", "keines", "keineswegs", "klar", "klare", "klaren", "klares", "klein",
    "kleinen", "kleiner", "kleines", "koennen", "koennt", "koennte", "koennten", "komme", "kommen", "kommt", "konkret",
    "konkrete", "konkreten", "konkreter", "konkretes", "können", "könnt", "künftig", "leider", "machen", "man",
    "manche", "manchem", "manchen", "mancher", "mancherorts", "manches", "manchmal", "mehr", "mehrere", "mein",
    "meine", "meinem", "meinen", "meiner", "meines", "mich", "mir", "mit", "mithin", "muessen", "muesst", "muesste",
    "muss", "musst", "musste", "mussten", "muß", "mußt", "müssen", "müsste", "müssten", "müßt", "müßte", "nach",
    "nachdem", "nachher", "nachhinein", "nahm", "natürlich", "neben", "nebenan", "nehmen", "nein", "nicht", "nichts",
    "nie", "niemals", "niemand", "nirgends", "nirgendwo", "noch", "nun", "nur", "nächste", "nämlich", "nötigenfalls",
    "ob", "oben", "oberhalb", "obgleich", "obschon", "obwohl", "oder", "oft", "per", "plötzlich", "schließlich",
    "schon", "sehr", "sehrwohl", "seid", "sein", "seine", "seinem", "seinen", "seiner", "seines", "seit", "seitdem",
    "seither", "selber", "selbst", "sich", "sicher", "sicherlich", "sie", "sind", "so", "sobald", "sodass", "sodaß",
    "soeben", "sofern", "sofort", "sogar", "solange", "solch", "solche", "solchem", "solchen", "solcher", "solches",
    "soll", "sollen", "sollst", "sollt", "sollte", "sollten", "solltest", "somit", "sondern", "sonst", "sonstwo",
    "sooft", "soviel", "soweit", "sowie", "sowohl", "tatsächlich", "tatsächlichen", "tatsächlicher", "tatsächliches",
    "trotzdem", "ueber", "um", "umso", "unbedingt", "und", "unmöglich", "unmögliche", "unmöglichen", "unmöglicher",
    "uns", "unser", "unser", "unsere", "unsere", "unserem", "unseren", "unserer", "unseres", "unter", "usw", "viel",
    "viele", "vielen", "vieler", "vieles", "vielleicht", "vielmals", "vom", "von", "vor", "voran", "vorher", "vorüber",
    "völlig", "wann", "war", "waren", "warst", "warum", "was", "weder", "weil", "weiter", "weitere", "weiterem",
    "weiteren", "weiterer", "weiteres", "weiterhin", "weiß", "welche", "welchem", "welchen", "welcher", "welches",
    "wem", "wen", "wenig", "wenige", "weniger", "wenigstens", "wenn", "wenngleich", "wer", "werde", "werden", "werdet",
    "weshalb", "wessen", "wichtig", "wie", "wieder", "wieso", "wieviel", "wiewohl", "will", "willst", "wir", "wird",
    "wirklich", "wirst", "wo", "wodurch", "wogegen", "woher", "wohin", "wohingegen", "wohl", "wohlweislich", "womit",
    "woraufhin", "woraus", "worin", "wurde", "wurden", "während", "währenddessen", "wär", "wäre", "wären", "würde",
    "würden", "z.B.", "zB", "zahlreich", "zeitweise", "zu", "zudem", "zuerst", "zufolge", "zugleich", "zuletzt", "zum",
    "zumal", "zur", "zurück", "zusammen", "zuviel", "zwar", "zwischen", "ähnlich", "übel", "über", "überall",
    "überallhin", "überdies", "übermorgen", "übrig", "übrigens"
]

FRENCH_STOPWORDS = [
    "a", "abord", "absolument", "afin", "ah", "ai", "aie", "aient", "aies", "ailleurs", "ainsi", "ait", "allaient",
    "allo", "allons", "allô", "alors", "anterieur", "anterieure", "anterieures", "apres", "après", "as", "assez",
    "attendu", "au", "aucun", "aucune", "aucuns", "aujourd", "aujourd'hui", "aupres", "auquel", "aura", "aurai",
    "auraient", "aurais", "aurait", "auras", "aurez", "auriez", "aurions", "aurons", "auront", "aussi", "autant",
    "autre", "autrefois", "autrement", "autres", "autrui", "aux", "auxquelles", "auxquels", "avaient", "avais",
    "avait", "avant", "avec", "avez", "aviez", "avions", "avoir", "avons", "ayant", "ayez", "ayons", "b", "bah", "bas",
    "basee", "bat", "beau", "beaucoup", "bien", "bigre", "bon", "boum", "bravo", "brrr", "c", "car", "ce", "ceci",
    "cela", "celle", "celle-ci", "celle-là", "celles", "celles-ci", "celles-là", "celui", "celui-ci", "celui-là",
    "celà", "cent", "cependant", "certain", "certaine", "certaines", "certains", "certes", "ces", "cet", "cette",
    "ceux", "ceux-ci", "ceux-là", "chacun", "chacune", "chaque", "cher", "chers", "chez", "chiche", "chut", "chère",
    "chères", "ci", "cinq", "cinquantaine", "cinquante", "cinquantième", "cinquième", "clac", "clic", "combien",
    "comme", "comment", "comparable", "comparables", "compris", "concernant", "contre", "couic", "crac", "d", "da",
    "dans", "de", "debout", "dedans", "dehors", "deja", "delà", "depuis", "dernier", "derniere", "derriere",
    "derrière", "des", "desormais", "desquelles", "desquels", "dessous", "dessus", "deux", "deuxième", "deuxièmement",
    "devant", "devers", "devra", "devrait", "different", "differentes", "differents", "différent", "différente",
    "différentes", "différents", "dire", "directe", "directement", "dit", "dite", "dits", "divers", "diverse",
    "diverses", "dix", "dix-huit", "dix-neuf", "dix-sept", "dixième", "doit", "doivent", "donc", "dont", "dos", "douze",
    "douzième", "dring", "droite", "du", "duquel", "durant", "dès", "début", "désormais", "e", "effet", "egale",
    "egalement", "egales", "eh", "elle", "elle-même", "elles", "elles-mêmes", "en", "encore", "enfin", "entre",
    "envers", "environ", "es", "essai", "est", "et", "etant", "etc", "etre", "eu", "eue", "eues", "euh", "eurent",
    "eus", "eusse", "eussent", "eusses", "eussiez", "eussions", "eut", "eux", "eux-mêmes", "exactement", "excepté",
    "extenso", "exterieur", "eûmes", "eût", "eûtes", "f", "fais", "faisaient", "faisant", "fait", "faites", "façon",
    "feront", "fi", "flac", "floc", "fois", "font", "force", "furent", "fus", "fusse", "fussent", "fusses", "fussiez",
    "fussions", "fut", "fûmes", "fût", "fûtes", "g", "gens", "h", "ha", "haut", "hein", "hem", "hep", "hi", "ho",
    "holà", "hop", "hormis", "hors", "hou", "houp", "hue", "hui", "huit", "huitième", "hum", "hurrah", "hé", "hélas",
    "i", "ici", "il", "ils", "importe", "j", "je", "jusqu", "jusque", "juste", "k", "l", "la", "laisser", "laquelle",
    "las", "le", "lequel", "les", "lesquelles", "lesquels", "leur", "leurs", "longtemps", "lors", "lorsque", "lui",
    "lui-meme", "lui-même", "là", "lès", "m", "ma", "maint", "maintenant", "mais", "malgre", "malgré", "maximale",
    "me", "meme", "memes", "merci", "mes", "mien", "mienne", "miennes", "miens", "mille", "mince", "mine", "minimale",
    "moi", "moi-meme", "moi-même", "moindres", "moins", "mon", "mot", "moyennant", "multiple", "multiples", "même",
    "mêmes", "n", "na", "naturel", "naturelle", "naturelles", "ne", "neanmoins", "necessaire", "necessairement", "neuf",
    "neuvième", "ni", "nombreuses", "nombreux", "nommés", "non", "nos", "notamment", "notre", "nous", "nous-mêmes",
    "nouveau", "nouveaux", "nul", "néanmoins", "nôtre", "nôtres", "o", "oh", "ohé", "ollé", "olé", "on", "ont", "onze",
    "onzième", "ore", "ou", "ouf", "ouias", "oust", "ouste", "outre", "ouvert", "ouverte", "ouverts", "o|", "où", "p",
    "paf", "pan", "par", "parce", "parfois", "parle", "parlent", "parler", "parmi", "parole", "parseme", "partant",
    "particulier", "particulière", "particulièrement", "pas", "passé", "pendant", "pense", "permet", "personne",
    "personnes", "peu", "peut", "peuvent", "peux", "pff", "pfft", "pfut", "pif", "pire", "pièce", "plein", "plouf",
    "plupart", "plus", "plusieurs", "plutôt", "possessif", "possessifs", "possible", "possibles", "pouah", "pour",
    "pourquoi", "pourrais", "pourrait", "pouvait", "prealable", "precisement", "premier", "première", "premièrement",
    "pres", "probable", "probante", "procedant", "proche", "près", "psitt", "pu", "puis", "puisque", "pur", "pure",
    "q", "qu", "quand", "quant", "quant-à-soi", "quanta", "quarante", "quatorze", "quatre", "quatre-vingt", "quatrième",
    "quatrièmement", "que", "quel", "quelconque", "quelle", "quelles", "quelqu'un", "quelque", "quelques", "quels",
    "qui", "quiconque", "quinze", "quoi", "quoique", "r", "rare", "rarement", "rares", "relative", "relativement",
    "remarquable", "rend", "rendre", "restant", "reste", "restent", "restrictif", "retour", "revoici", "revoilà",
    "rien", "s", "sa", "sacrebleu", "sait", "sans", "sapristi", "sauf", "se", "sein", "seize", "selon", "semblable",
    "semblaient", "semble", "semblent", "sent", "sept", "septième", "sera", "serai", "seraient", "serais", "serait",
    "seras", "serez", "seriez", "serions", "serons", "seront", "ses", "seul", "seule", "seulement", "si", "sien",
    "sienne", "siennes", "siens", "sinon", "six", "sixième", "soi", "soi-même", "soient", "sois", "soit", "soixante",
    "sommes", "son", "sont", "sous", "souvent", "soyez", "soyons", "specifique", "specifiques", "speculatif", "stop",
    "strictement", "subtiles", "suffisant", "suffisante", "suffit", "suis", "suit", "suivant", "suivante", "suivantes",
    "suivants", "suivre", "sujet", "superpose", "sur", "surtout", "t", "ta", "tac", "tandis", "tant", "tardive", "te",
    "tel", "telle", "tellement", "telles", "tels", "tenant", "tend", "tenir", "tente", "tes", "tic", "tien", "tienne",
    "tiennes", "tiens", "toc", "toi", "toi-même", "ton", "touchant", "toujours", "tous", "tout", "toute", "toutefois",
    "toutes", "treize", "trente", "tres", "trois", "troisième", "troisièmement", "trop", "très", "tsoin", "tsouin",
    "tu", "té", "u", "un", "une", "unes", "uniformement", "unique", "uniques", "uns", "v", "va", "vais", "valeur",
    "vas", "vers", "via", "vif", "vifs", "vingt", "vivat", "vive", "vives", "vlan", "voici", "voie", "voient", "voilà",
    "voire", "vont", "vos", "votre", "vous", "vous-mêmes", "vu", "vé", "vôtre", "vôtres", "w", "x", "y", "z", "zut",
    "à", "â", "ça", "ès", "étaient", "étais", "était", "étant", "état", "étiez", "étions", "été", "étée", "étées",
    "étés", "êtes", "être", "ô"
]

DUTCH_STOPWORDS = [ "aan", "aangaande", "aangezien", "achte", "achter", "achterna", "af", "afgelopen", "al", "aldaar",
                    "aldus", "alhoewel", "alias", "alle", "allebei", "alleen", "alles", "als", "alsnog", "altijd",
                    "altoos", "ander", "andere", "anders", "anderszins", "beetje", "behalve", "behoudens", "beide",
                    "beiden", "ben", "beneden", "bent", "bepaald", "betreffende", "bij", "bijna", "bijv", "binnen",
                    "binnenin", "blijkbaar", "blijken", "boven", "bovenal", "bovendien", "bovengenoemd", "bovenstaand",
                    "bovenvermeld", "buiten", "bv", "daar", "daardoor", "daarheen", "daarin", "daarna", "daarnet",
                    "daarom", "daarop", "daaruit", "daarvanlangs", "dan", "dat", "de", "deden", "deed", "der", "derde",
                    "derhalve", "dertig", "deze", "dhr", "die", "dikwijls", "dit", "doch", "doe", "doen", "doet", "door",
                    "doorgaand", "drie", "duizend", "dus", "echter", "een", "eens", "eer", "eerdat", "eerder", "eerlang",
                    "eerst", "eerste", "eigen", "eigenlijk", "elk", "elke", "en", "enig", "enige", "enigszins", "enkel",
                    "er", "erdoor", "erg", "ergens", "etc", "etcetera", "even", "eveneens", "evenwel", "gauw", "ge",
                    "gedurende", "geen", "gehad", "gekund", "geleden", "gelijk", "gemoeten", "gemogen", "genoeg",
                    "geweest", "gewoon", "gewoonweg", "haar", "haarzelf", "had", "hadden", "hare", "heb", "hebben",
                    "hebt", "hedden", "heeft", "heel", "hem", "hemzelf", "hen", "het", "hetzelfde", "hier", "hierbeneden",
                    "hierboven", "hierin", "hierna", "hierom", "hij", "hijzelf", "hoe", "hoewel", "honderd", "hun",
                    "hunne", "ieder", "iedere", "iedereen", "iemand", "iets", "ik", "ikzelf", "in", "inderdaad",
                    "inmiddels", "intussen", "inzake", "is", "ja", "je", "jezelf", "jij", "jijzelf", "jou", "jouw",
                    "jouwe", "juist", "jullie", "kan", "klaar", "kon", "konden", "krachtens", "kun", "kunnen", "kunt",
                    "laatst", "later", "liever", "lijken", "lijkt", "maak", "maakt", "maakte", "maakten", "maar", "mag",
                    "maken", "me", "meer", "meest", "meestal", "men", "met", "mevr", "mezelf", "mij", "mijn", "mijnent",
                    "mijner", "mijzelf", "minder", "miss", "misschien", "missen", "mits", "mocht", "mochten", "moest",
                    "moesten", "moet", "moeten", "mogen", "mr", "mrs", "mw", "na", "naar", "nadat", "nam", "namelijk",
                    "nee", "neem", "negen", "nemen", "nergens", "net", "niemand", "niet", "niets", "niks", "noch",
                    "nochtans", "nog", "nogal", "nooit", "nu", "nv", "of", "ofschoon", "om", "omdat", "omhoog", "omlaag",
                    "omstreeks", "omtrent", "omver", "ondanks", "onder", "ondertussen", "ongeveer", "ons", "onszelf",
                    "onze", "onzeker", "ooit", "ook", "op", "opnieuw", "opzij", "over", "overal", "overeind", "overige",
                    "overigens", "paar", "pas", "per", "precies", "recent", "redelijk", "reeds", "rond", "rondom",
                    "samen", "sedert", "sinds", "sindsdien", "slechts", "sommige", "spoedig", "steeds", "tamelijk",
                    "te", "tegen", "tegenover", "tenzij", "terwijl", "thans", "tien", "tiende", "tijdens", "tja", "toch",
                    "toe", "toen", "toenmaals", "toenmalig", "tot", "totdat", "tussen", "twee", "tweede", "u", "uit",
                    "uitgezonderd", "uw", "vaak", "vaakwat", "van", "vanaf", "vandaan", "vanuit", "vanwege", "veel",
                    "veeleer", "veertig", "verder", "verscheidene", "verschillende", "vervolgens", "via", "vier",
                    "vierde", "vijf", "vijfde", "vijftig", "vol", "volgend", "volgens", "voor", "vooraf", "vooral",
                    "vooralsnog", "voorbij", "voordat", "voordezen", "voordien", "voorheen", "voorop", "voorts",
                    "vooruit", "vrij", "vroeg", "waar", "waarom", "waarschijnlijk", "wanneer", "want", "waren", "was",
                    "wat", "we", "wederom", "weer", "weg", "wegens", "weinig", "wel", "weldra", "welk", "welke", "werd",
                    "werden", "werder", "wezen", "whatever", "wie", "wiens", "wier", "wij", "wijzelf", "wil", "wilden",
                    "willen", "word", "worden", "wordt", "zal", "ze", "zei", "zeker", "zelf", "zelfde", "zelfs", "zes",
                    "zeven", "zich", "zichzelf", "zij", "zijn", "zijne", "zijzelf", "zo", "zoals", "zodat", "zodra",
                    "zonder", "zou", "zouden", "zowat", "zulk", "zulke", "zullen", "zult" ]

ITALIAN_STOPWORDS = [ "a", "abbastanza", "abbia", "abbiamo", "abbiano", "abbiate", "accidenti", "ad", "adesso", "affinché",
                      "agl", "agli", "ahime", "ahimè", "ai", "al", "alcuna", "alcuni", "alcuno", "all", "alla", "alle",
                      "allo", "allora", "altre", "altri", "altrimenti", "altro", "altrove", "altrui", "anche", "ancora",
                      "anni", "anno", "ansa", "anticipo", "assai", "attesa", "attraverso", "avanti", "avemmo", "avendo",
                      "avente", "aver", "avere", "averlo", "avesse", "avessero", "avessi", "avessimo", "aveste", "avesti",
                      "avete", "aveva", "avevamo", "avevano", "avevate", "avevi", "avevo", "avrai", "avranno", "avrebbe",
                      "avrebbero", "avrei", "avremmo", "avremo", "avreste", "avresti", "avrete", "avrà", "avrò", "avuta",
                      "avute", "avuti", "avuto", "basta", "ben", "bene", "benissimo", "brava", "bravo", "buono", "c", "caso",
                      "cento", "certa", "certe", "certi", "certo", "che", "chi", "chicchessia", "chiunque", "ci",
                      "ciascuna", "ciascuno", "cima", "cinque", "cio", "cioe", "cioè", "circa", "citta", "città", "ciò",
                      "co", "codesta", "codesti", "codesto", "cogli", "coi", "col", "colei", "coll", "coloro", "colui",
                      "come", "cominci", "comprare", "comunque", "con", "concernente", "conclusione", "consecutivi",
                      "consecutivo", "consiglio", "contro", "cortesia", "cos", "cosa", "cosi", "così", "cui", "d", "da",
                      "dagl", "dagli", "dai", "dal", "dall", "dalla", "dalle", "dallo", "dappertutto", "davanti", "degl",
                      "degli", "dei", "del", "dell", "della", "delle", "dello", "dentro", "detto", "deve", "devo", "di",
                      "dice", "dietro", "dire", "dirimpetto", "diventa", "diventare", "diventato", "dopo", "doppio",
                      "dov", "dove", "dovra", "dovrà", "dovunque", "due", "dunque", "durante", "e", "ebbe", "ebbero",
                      "ebbi", "ecc", "ecco", "ed", "effettivamente", "egli", "ella", "entrambi", "eppure", "era",
                      "erano", "eravamo", "eravate", "eri", "ero", "esempio", "esse", "essendo", "esser", "essere",
                      "essi", "ex", "fa", "faccia", "facciamo", "facciano", "facciate", "faccio", "facemmo", "facendo",
                      "facesse", "facessero", "facessi", "facessimo", "faceste", "facesti", "faceva", "facevamo",
                      "facevano", "facevate", "facevi", "facevo", "fai", "fanno", "farai", "faranno", "fare", "farebbe",
                      "farebbero", "farei", "faremmo", "faremo", "fareste", "faresti", "farete", "farà", "farò", "fatto",
                      "favore", "fece", "fecero", "feci", "fin", "finalmente", "finche", "fine", "fino", "forse", "forza",
                      "fosse", "fossero", "fossi", "fossimo", "foste", "fosti", "fra", "frattempo", "fu", "fui", "fummo",
                      "fuori", "furono", "futuro", "generale", "gente", "gia", "giacche", "giorni", "giorno", "giu",
                      "già", "gli", "gliela", "gliele", "glieli", "glielo", "gliene", "grande", "grazie", "gruppo", "ha",
                      "haha", "hai", "hanno", "ho", "i", "ie", "ieri", "il", "improvviso", "in", "inc", "indietro",
                      "infatti", "inoltre", "insieme", "intanto", "intorno", "invece", "io", "l", "la", "lasciato",
                      "lato", "le", "lei", "li", "lo", "lontano", "loro", "lui", "lungo", "luogo", "là", "ma", "macche",
                      "magari", "maggior", "mai", "male", "malgrado", "malissimo", "me", "medesimo", "mediante",
                      "meglio", "meno", "mentre", "mesi", "mezzo", "mi", "mia", "mie", "miei", "mila", "miliardi",
                      "milioni", "minimi", "mio", "modo", "molta", "molti", "moltissimo", "molto", "momento", "mondo",
                      "ne", "negl", "negli", "nei", "nel", "nell", "nella", "nelle", "nello", "nemmeno", "neppure",
                      "nessun", "nessuna", "nessuno", "niente", "no", "noi", "nome", "non", "nondimeno", "nonostante",
                      "nonsia", "nostra", "nostre", "nostri", "nostro", "novanta", "nove", "nulla", "nuovi", "nuovo",
                      "o", "od", "oggi", "ogni", "ognuna", "ognuno", "oltre", "oppure", "ora", "ore", "osi", "ossia",
                      "ottanta", "otto", "paese", "parecchi", "parecchie", "parecchio", "parte", "partendo", "peccato",
                      "peggio", "per", "perche", "perchè", "perché", "percio", "perciò", "perfino", "pero", "persino",
                      "persone", "però", "piedi", "pieno", "piglia", "piu", "piuttosto", "più", "po", "pochissimo",
                      "poco", "poi", "poiche", "possa", "possedere", "posteriore", "posto", "potrebbe", "preferibilmente",
                      "presa", "press", "prima", "primo", "principalmente", "probabilmente", "promesso", "proprio",
                      "puo", "pure", "purtroppo", "può", "qua", "qualche", "qualcosa", "qualcuna", "qualcuno", "quale",
                      "quali", "qualunque", "quando", "quanta", "quante", "quanti", "quanto", "quantunque", "quarto",
                      "quasi", "quattro", "quel", "quella", "quelle", "quelli", "quello", "quest", "questa", "queste",
                      "questi", "questo", "qui", "quindi", "quinto", "realmente", "recente", "recentemente",
                      "registrazione", "relativo", "riecco", "rispetto", "salvo", "sara", "sarai", "saranno", "sarebbe",
                      "sarebbero", "sarei", "saremmo", "saremo", "sareste", "saresti", "sarete", "sarà", "sarò", "scola",
                      "scopo", "scorso", "se", "secondo", "seguente", "seguito", "sei", "sembra", "sembrare", "sembrato",
                      "sembrava", "sembri", "sempre", "senza", "sette", "si", "sia", "siamo", "siano", "siate", "siete",
                      "sig", "solito", "solo", "soltanto", "sono", "sopra", "soprattutto", "sotto", "spesso", "sta",
                      "stai", "stando", "stanno", "starai", "staranno", "starebbe", "starebbero", "starei", "staremmo",
                      "staremo", "stareste", "staresti", "starete", "starà", "starò", "stata", "state", "stati", "stato",
                      "stava", "stavamo", "stavano", "stavate", "stavi", "stavo", "stemmo", "stessa", "stesse",
                      "stessero", "stessi", "stessimo", "stesso", "steste", "stesti", "stette", "stettero", "stetti",
                      "stia", "stiamo", "stiano", "stiate", "sto", "su", "sua", "subito", "successivamente", "successivo",
                      "sue", "sugl", "sugli", "sui", "sul", "sull", "sulla", "sulle", "sullo", "suo", "suoi", "tale",
                      "tali", "talvolta", "tanto", "te", "tempo", "terzo", "th", "ti", "titolo", "tra", "tranne", "tre",
                      "trenta", "triplo", "troppo", "trovato", "tu", "tua", "tue", "tuo", "tuoi", "tutta", "tuttavia",
                      "tutte", "tutti", "tutto", "uguali", "ulteriore", "ultimo", "un", "una", "uno", "uomo", "va", "vai",
                      "vale", "vari", "varia", "varie", "vario", "verso", "vi", "vicino", "visto", "vita", "voi", "volta",
                      "volte", "vostra", "vostre", "vostri", "vostro", "è" ]

PORTUGUESE_STOPWORDS = [ "a", "acerca", "adeus", "agora", "ainda", "alem", "algmas", "algo", "algumas", "alguns", "ali",
                         "além", "ambas", "ambos", "ano", "anos", "antes", "ao", "aonde", "aos", "apenas", "apoio",
                         "apontar", "apos", "após", "aquela", "aquelas", "aquele", "aqueles", "aqui", "aquilo", "as",
                         "assim", "através", "atrás", "até", "aí", "baixo", "bastante", "bem", "boa", "boas", "bom",
                         "bons", "breve", "cada", "caminho", "catorze", "cedo", "cento", "certamente", "certeza", "cima",
                         "cinco", "coisa", "com", "como", "comprido", "conhecido", "conselho", "contra", "contudo",
                         "corrente", "cuja", "cujas", "cujo", "cujos", "custa", "cá", "da", "daquela", "daquelas",
                         "daquele", "daqueles", "dar", "das", "de", "debaixo", "dela", "delas", "dele", "deles", "demais",
                         "dentro", "depois", "desde", "desligado", "dessa", "dessas", "desse", "desses", "desta", "destas",
                         "deste", "destes", "deve", "devem", "deverá", "dez", "dezanove", "dezasseis", "dezassete",
                         "dezoito", "dia", "diante", "direita", "dispoe", "dispoem", "diversa", "diversas", "diversos",
                         "diz", "dizem", "dizer", "do", "dois", "dos", "doze", "duas", "durante", "dá", "dão", "dúvida",
                         "e", "ela", "elas", "ele", "eles", "em", "embora", "enquanto", "entao", "entre", "então", "era",
                         "eram", "essa", "essas", "esse", "esses", "esta", "estado", "estamos", "estar", "estará", "estas",
                         "estava", "estavam", "este", "esteja", "estejam", "estejamos", "estes", "esteve", "estive",
                         "estivemos", "estiver", "estivera", "estiveram", "estiverem", "estivermos", "estivesse",
                         "estivessem", "estiveste", "estivestes", "estivéramos", "estivéssemos", "estou", "está", "estás",
                         "estávamos", "estão", "eu", "exemplo", "falta", "fará", "favor", "faz", "fazeis", "fazem",
                         "fazemos", "fazer", "fazes", "fazia", "faço", "fez", "fim", "final", "foi", "fomos", "for",
                         "fora", "foram", "forem", "forma", "formos", "fosse", "fossem", "foste", "fostes", "fui",
                         "fôramos", "fôssemos", "geral", "grande", "grandes", "grupo", "ha", "haja", "hajam", "hajamos",
                         "havemos", "havia", "hei", "hoje", "hora", "horas", "houve", "houvemos", "houver", "houvera",
                         "houveram", "houverei", "houverem", "houveremos", "houveria", "houveriam", "houvermos",
                         "houverá", "houverão", "houveríamos", "houvesse", "houvessem", "houvéramos", "houvéssemos",
                         "há", "hão", "iniciar", "inicio", "ir", "irá", "isso", "ista", "iste", "isto", "já", "lado",
                         "lhe", "lhes", "ligado", "local", "logo", "longe", "lugar", "lá", "maior", "maioria", "maiorias",
                         "mais", "mal", "mas", "me", "mediante", "meio", "menor", "menos", "meses", "mesma", "mesmas",
                         "mesmo", "mesmos", "meu", "meus", "mil", "minha", "minhas", "momento", "muito", "muitos",
                         "máximo", "mês", "na", "nada", "nao", "naquela", "naquelas", "naquele", "naqueles", "nas", "nem",
                         "nenhuma", "nessa", "nessas", "nesse", "nesses", "nesta", "nestas", "neste", "nestes", "no",
                         "noite", "nome", "nos", "nossa", "nossas", "nosso", "nossos", "nova", "novas", "nove", "novo",
                         "novos", "num", "numa", "numas", "nunca", "nuns", "não", "nível", "nós", "número", "o", "obra",
                         "obrigada", "obrigado", "oitava", "oitavo", "oito", "onde", "ontem", "onze", "os", "ou", "outra",
                         "outras", "outro", "outros", "para", "parece", "parte", "partir", "paucas", "pegar", "pela",
                         "pelas", "pelo", "pelos", "perante", "perto", "pessoas", "pode", "podem", "poder", "poderá",
                         "podia", "pois", "ponto", "pontos", "por", "porque", "porquê", "portanto", "posição",
                         "possivelmente", "posso", "possível", "pouca", "pouco", "poucos", "povo", "primeira",
                         "primeiras", "primeiro", "primeiros", "promeiro", "propios", "proprio", "própria", "próprias",
                         "próprio", "próprios", "próxima", "próximas", "próximo", "próximos", "puderam", "pôde", "põe",
                         "põem", "quais", "qual", "qualquer", "quando", "quanto", "quarta", "quarto", "quatro", "que",
                         "quem", "quer", "quereis", "querem", "queremas", "queres", "quero", "questão", "quieto",
                         "quinta", "quinto", "quinze", "quáis", "quê", "relação", "sabe", "sabem", "saber", "se",
                         "segunda", "segundo", "sei", "seis", "seja", "sejam", "sejamos", "sem", "sempre", "sendo",
                         "ser", "serei", "seremos", "seria", "seriam", "será", "serão", "seríamos", "sete", "seu",
                         "seus", "sexta", "sexto", "sim", "sistema", "sob", "sobre", "sois", "somente", "somos", "sou",
                         "sua", "suas", "são", "sétima", "sétimo", "só", "tal", "talvez", "tambem", "também", "tanta",
                         "tantas", "tanto", "tarde", "te", "tem", "temos", "tempo", "tendes", "tenha", "tenham",
                         "tenhamos", "tenho", "tens", "tentar", "tentaram", "tente", "tentei", "ter", "terceira",
                         "terceiro", "terei", "teremos", "teria", "teriam", "terá", "terão", "teríamos", "teu", "teus",
                         "teve", "tinha", "tinham", "tipo", "tive", "tivemos", "tiver", "tivera", "tiveram", "tiverem",
                         "tivermos", "tivesse", "tivessem", "tiveste", "tivestes", "tivéramos", "tivéssemos", "toda",
                         "todas", "todo", "todos", "trabalhar", "trabalho", "treze", "três", "tu", "tua", "tuas", "tudo",
                         "tão", "tém", "têm", "tínhamos", "um", "uma", "umas", "uns", "usa", "usar", "vai", "vais",
                         "valor", "veja", "vem", "vens", "ver", "verdade", "verdadeiro", "vez", "vezes", "viagem",
                         "vindo", "vinte", "você", "vocês", "vos", "vossa", "vossas", "vosso", "vossos", "vários",
                         "vão", "vêm", "vós", "zero", "à", "às", "área", "é", "éramos", "és", "último" ]

RUSSIAN_STOPWORDS = [ "c", "а", "алло", "без", "белый", "близко", "более", "больше", "большой", "будем", "будет",
                      "будете", "будешь", "будто", "буду", "будут", "будь", "бы", "бывает", "бывь", "был", "была",
                      "были", "было", "быть", "в", "важная", "важное", "важные", "важный", "вам", "вами", "вас", "ваш",
                      "ваша", "ваше", "ваши", "вверх", "вдали", "вдруг", "ведь", "везде", "вернуться", "весь", "вечер",
                      "взгляд", "взять", "вид", "видел", "видеть", "вместе", "вне", "вниз", "внизу", "во", "вода",
                      "война", "вокруг", "вон", "вообще", "вопрос", "восемнадцатый", "восемнадцать", "восемь", "восьмой",
                      "вот", "впрочем", "времени", "время", "все", "все еще", "всегда", "всего", "всем", "всеми", "всему",
                      "всех", "всею", "всю", "всюду", "вся", "всё", "второй", "вы", "выйти", "г", "где", "главный", "глаз",
                      "говорил", "говорит", "говорить", "год", "года", "году", "голова", "голос", "город", "да", "давать",
                      "давно", "даже", "далекий", "далеко", "дальше", "даром", "дать", "два", "двадцатый", "двадцать",
                      "две", "двенадцатый", "двенадцать", "дверь", "двух", "девятнадцатый", "девятнадцать", "девятый",
                      "девять", "действительно", "дел", "делал", "делать", "делаю", "дело", "день", "деньги", "десятый",
                      "десять", "для", "до", "довольно", "долго", "должен", "должно", "должный", "дом", "дорога", "друг",
                      "другая", "другие", "других", "друго", "другое", "другой", "думать", "душа", "е", "его", "ее", "ей",
                      "ему", "если", "есть", "еще", "ещё", "ею", "её", "ж", "ждать", "же", "жена", "женщина", "жизнь",
                      "жить", "за", "занят", "занята", "занято", "заняты", "затем", "зато", "зачем", "здесь", "земля",
                      "знать", "значит", "значить", "и", "иди", "идти", "из", "или", "им", "имеет", "имел", "именно",
                      "иметь", "ими", "имя", "иногда", "их", "к", "каждая", "каждое", "каждые", "каждый", "кажется",
                      "казаться", "как", "какая", "какой", "кем", "книга", "когда", "кого", "ком", "комната", "кому",
                      "конец", "конечно", "которая", "которого", "которой", "которые", "который", "которых", "кроме",
                      "кругом", "кто", "куда", "лежать", "лет", "ли", "лицо", "лишь", "лучше", "любить", "люди", "м",
                      "маленький", "мало", "мать", "машина", "между", "меля", "менее", "меньше", "меня", "место",
                      "миллионов", "мимо", "минута", "мир", "мира", "мне", "много", "многочисленная", "многочисленное",
                      "многочисленные", "многочисленный", "мной", "мною", "мог", "могу", "могут", "мож", "может",
                      "может быть", "можно", "можхо", "мои", "мой", "мор", "москва", "мочь", "моя", "моё", "мы", "на",
                      "наверху", "над", "надо", "назад", "наиболее", "найти", "наконец", "нам", "нами", "народ", "нас",
                      "начала", "начать", "наш", "наша", "наше", "наши", "не", "него", "недавно", "недалеко", "нее",
                      "ней", "некоторый", "нельзя", "нем", "немного", "нему", "непрерывно", "нередко", "несколько",
                      "нет", "нею", "неё", "ни", "нибудь", "ниже", "низко", "никакой", "никогда", "никто", "никуда",
                      "ним", "ними", "них", "ничего", "ничто", "но", "новый", "нога", "ночь", "ну", "нужно", "нужный",
                      "нх", "о", "об", "оба", "обычно", "один", "одиннадцатый", "одиннадцать", "однажды", "однако",
                      "одного", "одной", "оказаться", "окно", "около", "он", "она", "они", "оно", "опять", "особенно",
                      "остаться", "от", "ответить", "отец", "откуда", "отовсюду", "отсюда", "очень", "первый", "перед",
                      "писать", "плечо", "по", "под", "подойди", "подумать", "пожалуйста", "позже", "пойти", "пока",
                      "пол", "получить", "помнить", "понимать", "понять", "пор", "пора", "после", "последний",
                      "посмотреть", "посреди", "потом", "потому", "почему", "почти", "правда", "прекрасно", "при", "про",
                      "просто", "против", "процентов", "путь", "пятнадцатый", "пятнадцать", "пятый", "пять", "работа",
                      "работать", "раз", "разве", "рано", "раньше", "ребенок", "решить", "россия", "рука", "русский",
                      "ряд", "рядом", "с", "с кем", "сам", "сама", "сами", "самим", "самими", "самих", "само", "самого",
                      "самой", "самом", "самому", "саму", "самый", "свет", "свое", "своего", "своей", "свои", "своих",
                      "свой", "свою", "сделать", "сеаой", "себе", "себя", "сегодня", "седьмой", "сейчас", "семнадцатый",
                      "семнадцать", "семь", "сидеть", "сила", "сих", "сказал", "сказала", "сказать", "сколько", "слишком",
                      "слово", "случай", "смотреть", "сначала", "снова", "со", "собой", "собою", "советский", "совсем",
                      "спасибо", "спросить", "сразу", "стал", "старый", "стать", "стол", "сторона", "стоять", "страна",
                      "суть", "считать", "т", "та", "так", "такая", "также", "таки", "такие", "такое", "такой", "там",
                      "твои", "твой", "твоя", "твоё", "те", "тебе", "тебя", "тем", "теми", "теперь", "тех", "то", "тобой",
                      "тобою", "товарищ", "тогда", "того", "тоже", "только", "том", "тому", "тот", "тою", "третий", "три",
                      "тринадцатый", "тринадцать", "ту", "туда", "тут", "ты", "тысяч", "у", "увидеть", "уж", "уже", "улица",
                      "уметь", "утро", "хороший", "хорошо", "хотел бы", "хотеть", "хоть", "хотя", "хочешь", "час",
                      "часто", "часть", "чаще", "чего", "человек", "чем", "чему", "через", "четвертый", "четыре",
                      "четырнадцатый", "четырнадцать", "что", "чтоб", "чтобы", "чуть", "шестнадцатый", "шестнадцать",
                      "шестой", "шесть", "эта", "эти", "этим", "этими", "этих", "это", "этого", "этой", "этом", "этому",
                      "этот", "эту", "я", "являюсь" ]

SPANISH_STOPWORDS = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "_", "a", "actualmente", "acuerdo", "adelante",
                      "ademas", "además", "adrede", "afirmó", "agregó", "ahi", "ahora", "ahí", "al", "algo", "alguna",
                      "algunas", "alguno", "algunos", "algún", "alli", "allí", "alrededor", "ambos", "ampleamos",
                      "antano", "antaño", "ante", "anterior", "antes", "apenas", "aproximadamente", "aquel", "aquella",
                      "aquellas", "aquello", "aquellos", "aqui", "aquél", "aquélla", "aquéllas", "aquéllos", "aquí",
                      "arriba", "arribaabajo", "aseguró", "asi", "así", "atras", "aun", "aunque", "ayer", "añadió",
                      "aún", "b", "bajo", "bastante", "bien", "breve", "buen", "buena", "buenas", "bueno", "buenos",
                      "c", "cada", "casi", "cerca", "cierta", "ciertas", "cierto", "ciertos", "cinco", "claro", "comentó",
                      "como", "con", "conmigo", "conocer", "conseguimos", "conseguir", "considera", "consideró", "consigo",
                      "consigue", "consiguen", "consigues", "contigo", "contra", "cosas", "creo", "cual", "cuales",
                      "cualquier", "cuando", "cuanta", "cuantas", "cuanto", "cuantos", "cuatro", "cuenta", "cuál",
                      "cuáles", "cuándo", "cuánta", "cuántas", "cuánto", "cuántos", "cómo", "d", "da", "dado", "dan",
                      "dar", "de", "debajo", "debe", "deben", "debido", "decir", "dejó", "del", "delante", "demasiado",
                      "demás", "dentro", "deprisa", "desde", "despacio", "despues", "después", "detras", "detrás", "dia",
                      "dias", "dice", "dicen", "dicho", "dieron", "diferente", "diferentes", "dijeron", "dijo", "dio",
                      "donde", "dos", "durante", "día", "días", "dónde", "e", "ejemplo", "el", "ella", "ellas", "ello",
                      "ellos", "embargo", "empleais", "emplean", "emplear", "empleas", "empleo", "en", "encima", "encuentra",
                      "enfrente", "enseguida", "entonces", "entre", "era", "erais", "eramos", "eran", "eras", "eres",
                      "es", "esa", "esas", "ese", "eso", "esos", "esta", "estaba", "estabais", "estaban", "estabas",
                      "estad", "estada", "estadas", "estado", "estados", "estais", "estamos", "estan", "estando", "estar",
                      "estaremos", "estará", "estarán", "estarás", "estaré", "estaréis", "estaría", "estaríais",
                      "estaríamos", "estarían", "estarías", "estas", "este", "estemos", "esto", "estos", "estoy", "estuve",
                      "estuviera", "estuvierais", "estuvieran", "estuvieras", "estuvieron", "estuviese", "estuvieseis",
                      "estuviesen", "estuvieses", "estuvimos", "estuviste", "estuvisteis", "estuviéramos", "estuviésemos",
                      "estuvo", "está", "estábamos", "estáis", "están", "estás", "esté", "estéis", "estén", "estés", "ex",
                      "excepto", "existe", "existen", "explicó", "expresó", "f", "fin", "final", "fue", "fuera", "fuerais",
                      "fueran", "fueras", "fueron", "fuese", "fueseis", "fuesen", "fueses", "fui", "fuimos", "fuiste",
                      "fuisteis", "fuéramos", "fuésemos", "g", "general", "gran", "grandes", "gueno", "h", "ha", "haber",
                      "habia", "habida", "habidas", "habido", "habidos", "habiendo", "habla", "hablan", "habremos", "habrá",
                      "habrán", "habrás", "habré", "habréis", "habría", "habríais", "habríamos", "habrían", "habrías",
                      "habéis", "había", "habíais", "habíamos", "habían", "habías", "hace", "haceis", "hacemos", "hacen",
                      "hacer", "hacerlo", "haces", "hacia", "haciendo", "hago", "han", "has", "hasta", "hay", "haya",
                      "hayamos", "hayan", "hayas", "hayáis", "he", "hecho", "hemos", "hicieron", "hizo", "horas", "hoy",
                      "hube", "hubiera", "hubierais", "hubieran", "hubieras", "hubieron", "hubiese", "hubieseis",
                      "hubiesen", "hubieses", "hubimos", "hubiste", "hubisteis", "hubiéramos", "hubiésemos", "hubo", "i",
                      "igual", "incluso", "indicó", "informo", "informó", "intenta", "intentais", "intentamos", "intentan",
                      "intentar", "intentas", "intento", "ir", "j", "junto", "k", "l", "la", "lado", "largo", "las",
                      "le", "lejos", "les", "llegó", "lleva", "llevar", "lo", "los", "luego", "lugar", "m", "mal",
                      "manera", "manifestó", "mas", "mayor", "me", "mediante", "medio", "mejor", "mencionó", "menos",
                      "menudo", "mi", "mia", "mias", "mientras", "mio", "mios", "mis", "misma", "mismas", "mismo",
                      "mismos", "modo", "momento", "mucha", "muchas", "mucho", "muchos", "muy", "más", "mí", "mía",
                      "mías", "mío", "míos", "n", "nada", "nadie", "ni", "ninguna", "ningunas", "ninguno", "ningunos",
                      "ningún", "no", "nos", "nosotras", "nosotros", "nuestra", "nuestras", "nuestro", "nuestros",
                      "nueva", "nuevas", "nuevo", "nuevos", "nunca", "o", "ocho", "os", "otra", "otras", "otro", "otros",
                      "p", "pais", "para", "parece", "parte", "partir", "pasada", "pasado", "paìs", "peor", "pero",
                      "pesar", "poca", "pocas", "poco", "pocos", "podeis", "podemos", "poder", "podria", "podriais",
                      "podriamos", "podrian", "podrias", "podrá", "podrán", "podría", "podrían", "poner", "por", "por qué",
                      "porque", "posible", "primer", "primera", "primero", "primeros", "principalmente", "pronto", "propia",
                      "propias", "propio", "propios", "proximo", "próximo", "próximos", "pudo", "pueda", "puede",
                      "pueden", "puedo", "pues", "q", "qeu", "que", "quedó", "queremos", "quien", "quienes", "quiere",
                      "quiza", "quizas", "quizá", "quizás", "quién", "quiénes", "qué", "r", "raras", "realizado",
                      "realizar", "realizó", "repente", "respecto", "s", "sabe", "sabeis", "sabemos", "saben", "saber",
                      "sabes", "sal", "salvo", "se", "sea", "seamos", "sean", "seas", "segun", "segunda", "segundo",
                      "según", "seis", "ser", "sera", "seremos", "será", "serán", "serás", "seré", "seréis", "sería",
                      "seríais", "seríamos", "serían", "serías", "seáis", "señaló", "si", "sido", "siempre", "siendo",
                      "siete", "sigue", "siguiente", "sin", "sino", "sobre", "sois", "sola", "solamente", "solas",
                      "solo", "solos", "somos", "son", "soy", "soyos", "su", "supuesto", "sus", "suya", "suyas", "suyo",
                      "suyos", "sé", "sí", "sólo", "t", "tal", "tambien", "también", "tampoco", "tan", "tanto", "tarde",
                      "te", "temprano", "tendremos", "tendrá", "tendrán", "tendrás", "tendré", "tendréis", "tendría",
                      "tendríais", "tendríamos", "tendrían", "tendrías", "tened", "teneis", "tenemos", "tener", "tenga",
                      "tengamos", "tengan", "tengas", "tengo", "tengáis", "tenida", "tenidas", "tenido", "tenidos",
                      "teniendo", "tenéis", "tenía", "teníais", "teníamos", "tenían", "tenías", "tercera", "ti", "tiempo",
                      "tiene", "tienen", "tienes", "toda", "todas", "todavia", "todavía", "todo", "todos", "total",
                      "trabaja", "trabajais", "trabajamos", "trabajan", "trabajar", "trabajas", "trabajo", "tras",
                      "trata", "través", "tres", "tu", "tus", "tuve", "tuviera", "tuvierais", "tuvieran", "tuvieras",
                      "tuvieron", "tuviese", "tuvieseis", "tuviesen", "tuvieses", "tuvimos", "tuviste", "tuvisteis",
                      "tuviéramos", "tuviésemos", "tuvo", "tuya", "tuyas", "tuyo", "tuyos", "tú", "u", "ultimo", "un",
                      "una", "unas", "uno", "unos", "usa", "usais", "usamos", "usan", "usar", "usas", "uso", "usted",
                      "ustedes", "v", "va", "vais", "valor", "vamos", "van", "varias", "varios", "vaya", "veces", "ver",
                      "verdad", "verdadera", "verdadero", "vez", "vosotras", "vosotros", "voy", "vuestra", "vuestras",
                      "vuestro", "vuestros", "w", "x", "y", "ya", "yo", "z", "él", "éramos", "ésa", "ésas", "ése", "ésos",
                      "ésta", "éstas", "éste", "éstos", "última", "últimas", "último", "últimos" ]

STOPWORDS = {"pl": POLISH_STOPWORDS, "en": ENGLISH_STOPWORDS, "de": GERMAN_STOPWORDS, "fr": FRENCH_STOPWORDS,
             "nl": DUTCH_STOPWORDS, "it": ITALIAN_STOPWORDS, "pt": PORTUGUESE_STOPWORDS, "ru": RUSSIAN_STOPWORDS,
             "es" : SPANISH_STOPWORDS}


class FSTLemmatizer:

    def __init__(self, data_path: str, lang: str):
        self.lang = lang
        self.lemmatizer = Map(path=f"{data_path}.fst")
        self.lemmas = load(f"{data_path}_lemmas.bin")

    def lemma(self, word: str):
        word = word.lower()
        if word in self.lemmatizer: return self.lemmas[self.lemmatizer[word]]
        else: return word

    def __call__(self, tokens: List[str]):
        return [self.lemma(token) for token in tokens]


def get_lemmatizer(lang: str) -> FSTLemmatizer:
    current_dir = os.path.dirname(os.path.realpath(__file__))
    resource_path = os.path.join(current_dir, "resources", f"{lang}_lemmatizer_lower")
    return FSTLemmatizer(resource_path, lang)


def get_stopwords(lang: str):
    return STOPWORDS[lang]
